GET http://localhost:5000/api/tags

###

POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "user": {
    "username": "chayon",
    "email": "chayon@email.com",
    "password": "testpass"
  }
}

###

POST http://localhost:5000/api/v1/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlZDY2YjhjNzVjNWY1NWM1NTllZjU5MCIsInVzZXJuYW1lIjoiY2hheW9uIiwiZXhwIjoxNTk2Mjk0OTU2LCJpYXQiOjE1OTExMTA5NTZ9.zHH7LNYIXtdmepuIznumAI5SKM_ovcW4cMIBuho_Jkk

{
  "article": {
    "title": "This is a title",
    "description": "This is a description",
    "body": "This is a body",
    "tagList": [
      "dream",
      "heaven"
    ]
  }
}

###

POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
  "user":{
    "email": "chayon@email.com",
    "password": "testpass"
  }
}

###

POST http://localhost:5000/api/token
Content-Type: application/json

{
  "username": "foyez",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNjM4YjdkMzU5ZTMwMzk4MzVmMzBmZCIsInVzZXJuYW1lIjoiZm95ZXoiLCJpYXQiOjE1ODUwNjkzMjJ9.Hsb8AqCMAb4OrV6DR0Tg3MiCbXdPmt-QLUH6h6fcUDU"
}

###

DELETE http://localhost:5000/api/token/reject
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNjM4YjdkMzU5ZTMwMzk4MzVmMzBmZCIsInVzZXJuYW1lIjoiZm95ZXoiLCJpYXQiOjE1ODUwNjkzMjJ9.Hsb8AqCMAb4OrV6DR0Tg3MiCbXdPmt-QLUH6h6fcUDU"
}

###

GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNjM4YjdkMzU5ZTMwMzk4MzVmMzBmZCIsInVzZXJuYW1lIjoiZm95ZXoiLCJleHAiOjE1ODUwNTI0NDAsImlhdCI6MTU4NTA1MjQyMH0.6YK2EA37wxVbUcSI_7828_w4LwyxQPm2zVKgdhzu8lU